import { StyleSheet } from 'react-native';

export const createStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
    padding: 24,
  },
  containerChallenge: {
    flex: 1,
    backgroundColor: theme.colors.background,
    padding: 16,
  },
  surface: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 20,
    marginVertical: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 24,
    marginVertical: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    alignItems: 'center',
  },
  progressCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    alignItems: 'center',
    width: '100%',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
    color: theme.colors.onBackground,
    textAlign: 'center',
  },
  titleChallenge: {
    fontSize: 24,
    fontWeight: '600',
    color: theme.colors.onBackground,
    marginBottom: 16,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 12,
    color: theme.colors.onBackground,
  },
  label: {
    fontSize: 14,
    color: theme.colors.onSurfaceVariant,
    marginBottom: 4,
    textTransform: 'uppercase',
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  labelChallenge: {
    fontSize: 12,
    color: theme.colors.onSurfaceVariant,
    marginBottom: 4,
    textTransform: 'uppercase',
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  value: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.colors.onSurface,
    marginBottom: 16,
  },
  valueChallenge: {
    fontSize: 20,
    fontWeight: '600',
    color: theme.colors.onSurface,
    marginBottom: 8,
  },
  button: {
    backgroundColor: theme.colors.primary,
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginTop: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonSecondary: {
    backgroundColor: theme.colors.error,
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginTop: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonText: {
    color: theme.colors.onPrimary,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  buttonTextSecondary: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  depositsList: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
    minHeight: 80,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  empty: {
    fontSize: 16,
    color: theme.colors.onSurfaceVariant,
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
  depositItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.outline,
    paddingVertical: 12,
  },
  depositValue: {
    fontSize: 16,
    color: theme.colors.onSurface,
    fontWeight: '500',
  },
  // Challenge specific styles
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  grid: {
    paddingBottom: 24,
    alignItems: 'stretch',
    justifyContent: 'space-evenly'
  },
  cell: {
    marginHorizontal: 0.2,
    marginVertical: 1,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    flexBasis: '16.2%',
    maxWidth: '16.2%',
    height: 64,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  cellMarked: {
    backgroundColor: theme.colors.primaryContainer,
    borderColor: theme.colors.primary,
  },
  cellText: {
    fontSize: 14,
    color: theme.colors.onSurface,
    fontWeight: '600',
  },
  cellTextMarked: {
    color: theme.colors.primary,
    fontWeight: '700',
  },
  checkIcon: {
    marginLeft: 4,
  },
  // Progress styles
  progressContainer: {
    alignItems: 'center',
    marginBottom: 24,
    width: '100%',
  },
  progressText: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.onSurface,
    marginBottom: 16,
    textAlign: 'center',
  },
  progressBar: {
    width: '100%',
    height: 8,
    backgroundColor: theme.colors.outline,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.colors.secondary,
    borderRadius: 4,
  },
  successText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.secondary,
    marginTop: 16,
    textAlign: 'center',
  },
  // Theme toggle button
  themeToggle: {
    position: 'absolute',
    top: 10,
    right: 16,
    backgroundColor: theme.colors.surfaceVariant,
    borderRadius: 20,
    padding: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.primary,
  },
});
