import { StyleSheet } from 'react-native';

export const sharedStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f7fa',
    padding: 24,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  containerChallenge: {
    flex: 1,
    backgroundColor: '#f7f7fa',
    padding: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 24,
    color: '#1a2236',
    letterSpacing: 1,
    textAlign: 'center',
  },
  titleChallenge: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1a2236',
    marginBottom: 8,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  card: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  progressCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 1,
    alignItems: 'center',
    width: '90%',
  },
  label: {
    fontSize: 15,
    color: '#6c7a93',
    marginTop: 8,
    marginBottom: 2,
  },
  labelChallenge: {
    fontSize: 14,
    color: '#6c7a93',
    marginTop: 4,
    marginBottom: 2,
  },
  value: {
    fontSize: 22,
    fontWeight: '600',
    color: '#1a2236',
    marginBottom: 8,
  },
  valueChallenge: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a2236',
    marginBottom: 4,
  },
  button: {
    marginTop: 18,
    backgroundColor: '#1a2236',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 17,
    fontWeight: 'bold',
    marginTop: 8,
    marginBottom: 12,
    color: '#1a2236',
    alignSelf: 'flex-start',
  },
  depositsList: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    minHeight: 60,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  empty: {
    fontSize: 15,
    color: '#6c7a93',
    textAlign: 'center',
    marginTop: 8,
  },
  depositItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ececf0',
    paddingVertical: 6,
  },
  depositValue: {
    fontSize: 16,
    color: '#1a2236',
    fontWeight: '500',
  },
  // Estilos específicos do challenge
  header: {
    alignItems: 'center',
    marginBottom: 18,
  },
  grid: {
    paddingBottom: 24,
    alignItems: 'center',
  },
  cell: {
    margin: 6,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: '#ececf0',
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 60,
    elevation: 1,
    flexDirection: 'row',
  },
  cellMarked: {
    backgroundColor: '#e6eaf3',
    borderColor: '#b5b9c9',
    opacity: 0.7,
  },
  cellText: {
    fontSize: 16,
    color: '#1a2236',
    fontWeight: '500',
  },
  cellTextMarked: {
    color: '#6c7a93',
    fontWeight: '700',
  },
  checkIcon: {
    marginLeft: 6,
  },
  // Estilos para progress
  progressContainer: {
    alignItems: 'center',
    marginBottom: 18,
    width: '100%',
  },
  progressText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a2236',
    marginBottom: 12,
  },
  progressBar: {
    width: '100%',
    height: 8,
    backgroundColor: '#ececf0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
    borderRadius: 4,
  },
  successText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4CAF50',
    marginTop: 12,
    textAlign: 'center',
  },
  // Estilos para challenge grid
  challengeGrid: {
    paddingBottom: 24,
    alignItems: 'center',
  },
  challengeButton: {
    margin: 4,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#ececf0',
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#fff',
    justifyContent: 'center',
    minWidth: 50,
    elevation: 1,
    flexDirection: 'row',
  },
  challengeButtonPressed: {
    backgroundColor: '#1a2236',
    borderColor: '#1a2236',
  },
  challengeButtonText: {
    fontSize: 14,
    color: '#1a2236',
    fontWeight: '500',
  },
  challengeButtonTextPressed: {
    color: '#fff',
    fontWeight: '600',
  },
});
